language: python
dist: xenial
python:
  - "3.5"
addons:
  apt:
    packages:
    - enchant
    - hunspell-eu
    - myspell-en-au
    - myspell-en-gb
    - myspell-en-us
    - myspell-en-za
    - myspell-es
    - myspell-fr
    - myspell-pt

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install -r docs/requirements.txt
  - python setup.py install
  - pip install codecov
  - pip install flake8
  - pip install twine
  - python -m nltk.downloader stopwords

script:
  - flake8 . --exclude=.svn,CVS,.bzr,.hg,.git,__pycache__,.tox,.eggs,*.egg,docs,examples
  - coverage run --source articlequality -m pytest . -m "not nottravis"
  - sphinx-build -anW -b html docs dist/docs
  - sphinx-build -b linkcheck docs dist/docs

after_success:
  - coverage report
  - codecov

notifications:
  irc:
    channels:
      - "chat.freenode.net#wikimedia-ai"
    on_success: change
    on_failure: change
    template:
      - "%{repository_slug}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} %{build_url}"

#deploy:
#  provider: script
#  script: bash scripts/deploy.sh
#  on:
#    branch: master
